# Generated by Django 4.0.3 on 2022-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=10)),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('PASSWORD', models.CharField(max_length=20)),
                ('POINT', models.IntegerField()),
            ],
        ),
    ]
