# Generated by Django 4.1.3 on 2023-01-06 16:25

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APP_LINK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("USER_PHONE", models.CharField(max_length=20)),
                ("APP_ID", models.CharField(max_length=10)),
                ("APP_USER_ID", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NAME", models.CharField(max_length=10)),
                ("PHONE_NUMBER", models.CharField(max_length=100)),
                ("PASSWORD", models.CharField(max_length=20)),
                ("POINT", models.IntegerField()),
                ("PHOTO", models.FileField(upload_to="")),
                ("MYPHOTO", models.FileField(upload_to="")),
                ("AC_CODE", models.CharField(max_length=43)),
            ],
        ),
        migrations.CreateModel(
            name="DRIVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("USER_PHONE", models.CharField(max_length=20)),
                ("NAME", models.CharField(max_length=20)),
                ("TIME", models.DateTimeField()),
                ("USING", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EXCHANGE",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("USER_PHONE", models.CharField(max_length=10)),
                ("DATE", models.DateTimeField()),
                ("COST", models.IntegerField()),
                ("ITEM_ID", models.IntegerField()),
                ("ITEM_NAME", models.CharField(max_length=20)),
                ("USED", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EXCHANGE_ITEM",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("NAME", models.CharField(max_length=20)),
                ("COST", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HISTORY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("USER_PHONE", models.CharField(max_length=20)),
                ("APP_ID", models.CharField(max_length=10)),
                ("DATE", models.DateTimeField()),
                ("POINT", models.IntegerField()),
                ("DETAIL", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LOGIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FKcheck",
                    models.CharField(default=myapp.models.UUIDrand, max_length=36),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("Raccesscode", models.CharField(max_length=43)),
            ],
        ),
    ]
