# Generated by Django 4.1.3 on 2023-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="TANPI",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drive",
            name="TANPI",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchange",
            name="TANPI",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchange_item",
            name="TANPI",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="TANPI",
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="USER_PHONE",
            field=models.CharField(max_length=100),
        ),
    ]
