# Generated by Django 4.1.3 on 2023-01-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_client_tanpi_drive_tanpi_exchange_tanpi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="MYPHOTO",
        ),
    ]
