# Generated by Django 4.1.4 on 2022-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_student_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP_LINK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_PHONE', models.CharField(max_length=20)),
                ('APP_ID', models.CharField(max_length=10)),
                ('APP_USER_ID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EXCHANGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_PHONE', models.CharField(max_length=10)),
                ('COST', models.IntegerField()),
                ('ITEM_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EXCHANGE_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HISTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_PHONE', models.CharField(max_length=20)),
                ('APP_ID', models.CharField(max_length=10)),
                ('POINT', models.IntegerField()),
                ('DETAIL', models.CharField(max_length=50)),
            ],
        ),
    ]
