# Generated by Django 4.0.3 on 2022-12-27 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_app_link_exchange_exchange_item_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='PHOTO',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
