# Generated by Django 4.1.3 on 2023-01-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_client_myphoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="PHOTO",
            new_name="MYPHOTO",
        ),
    ]
