# Generated by Django 4.1.4 on 2022-12-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='photo',
            new_name='PHOTO',
        ),
    ]
