# Generated by Django 4.0.3 on 2022-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_item',
            name='COST',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
