# Generated by Django 4.1.4 on 2022-12-29 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_exchange_item_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_item',
            name='id',
        ),
        migrations.AddField(
            model_name='exchange_item',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
