# Generated by Django 4.1.4 on 2023-01-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_myphoto_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PASSBOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_PHONE', models.CharField(max_length=20)),
                ('APP_ID', models.CharField(max_length=10)),
                ('DATE', models.DateTimeField()),
                ('POINT', models.IntegerField()),
                ('DETAIL', models.CharField(max_length=50)),
                ('TANPI', models.IntegerField()),
                ('isHISTORY', models.BooleanField()),
                ('REMAIN', models.IntegerField()),
            ],
        ),
    ]
