# Generated by Django 4.1.4 on 2023-01-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_passbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_link',
            name='USER_PHONE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drive',
            name='USER_PHONE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='USER_PHONE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passbook',
            name='USER_PHONE',
            field=models.CharField(max_length=100),
        ),
    ]
