# Generated by Django 4.1.4 on 2022-12-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_exchange_item_id_exchange_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EXCHANGE_ITEM',
        ),
    ]
