# Generated by Django 4.1.4 on 2022-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_exchange_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXCHANGE_ITEM',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=20)),
                ('COST', models.IntegerField()),
            ],
        ),
    ]
