# Generated by Django 4.1.4 on 2022-12-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_exchange_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='DATE',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='DATE',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
