# Generated by Django 4.1.4 on 2023-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_exchange_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='USED',
            field=models.BooleanField(default=bool),
            preserve_default=False,
        ),
    ]
