# Generated by Django 4.1.4 on 2023-01-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_exchange_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='id',
        ),
        migrations.AddField(
            model_name='exchange',
            name='ID',
            field=models.AutoField(default=int, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
