# Generated by Django 4.1.3 on 2023-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_exchange_id_exchange_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DRIVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("USER_PHONE", models.CharField(max_length=20)),
                ("NAME", models.CharField(max_length=20)),
                ("TIME", models.TimeField()),
                ("USING", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="exchange",
            name="DATE",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="history",
            name="DATE",
            field=models.DateTimeField(),
        ),
    ]
