# Generated by Django 4.1.3 on 2023-01-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_drive_alter_exchange_date_alter_history_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drive",
            name="TIME",
            field=models.DateTimeField(),
        ),
    ]
