# Generated by Django 4.1.3 on 2023-01-05 14:59

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_drive_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rand4num",
                    models.CharField(default=myapp.models.UUIDrand, max_length=36),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("Raccesscode", models.CharField(max_length=43)),
            ],
        ),
        migrations.AlterField(
            model_name="client",
            name="PHONE_NUMBER",
            field=models.CharField(max_length=100),
        ),
    ]
