# Generated by Django 4.1.3 on 2023-01-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_login_alter_client_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="rand4num",
            new_name="FKcheck",
        ),
    ]
